language: node_js

branches:
  only:
  - master

sudo: false

matrix:
    include:
        - dist: bionic

script:
    - npm install
    - npm run build

deploy:
   provider: pages
   skip_cleanup: true
   local_dir: ./_book
   github_token: $GH_REPO_TOKEN
   on:
      branch: master
      dist: bionic