version: '3.8'

networks:
  default:
    driver: overlay
    internal: false

services:
  app:
    # Must have a pre-build docker image.
    image: twitter_cfdspace:latest
    networks:
      - default
    environment:
      # API keys and ACCESS tokens.
      - TWITTER_API_KEY=<REPLACE_WITH_TWITTER_API_KEY>
      - TWITTER_API_KEY_SECRET=<REPLACE_WITH_TWITTER_API_KEY_SECRET_HERE>
      - TWITTER_ACCESS_TOKEN=<REPLACE_WITH_TWITTER_ACCESS_TOKEN_HERE>
      - TWITTER_ACCESS_TOKEN_SECRET=<REPLACE_WITH_TWITTER_ACCESS_TOKEN_SECRET_HERE>
      # mongodb access details. Must match with admin credentials below.
      - MONGO_USER=<REPLACE_WITH_MONGODB_USER>
      - MONGO_PASSWORD=<REPLACE_WITH_MONGODB_PASSWORD>
      - MONGO_HOST=db
      - MONGO_DB=cfdspace
    volumes:
      - type: bind
        source: ./logs
        target: /var/log
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      replicas: 1
      placement:
        constraints: [node.role == manager]
  db:
    image: mongo:4-bionic
    networks:
      - default
    ports:
      - '27017:27017'
    environment:
      # mongodb admin credentials.
      - MONGO_INITDB_ROOT_USERNAME=<REPLACE_WITH_MONGODB_USER>
      - MONGO_INITDB_ROOT_PASSWORD=<REPLACE_WITH_MONGODB_PASSWORD>
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      replicas: 1
