# docker image build -f Dockerfile.compose -t cfdspace:latest .
FROM python:3.8-alpine

COPY config.py /bot/
COPY __init__.py /bot/
COPY main.py /bot/
COPY api_helper.py /bot/
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

WORKDIR /bot
CMD ["python3", "main.py"]
